import "./globals.css";
import React from "react";
import type {Metadata} from "next";
import localFont from "next/font/local";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Suspense tests",
  description: "Generated by create next app",
};

export default ({children}: Readonly<{ children: React.ReactNode }>) => (
  <html lang="en">
  <body className={`${geistSans.variable} ${geistMono.variable}`}>
  {children}
  </body>
  </html>
)
